<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('ZF2 ' . $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/assets/css/custom.css')
        ->prependStylesheet($this->basePath() . '/assets/css/style-responsive.css')
        ->prependStylesheet($this->basePath() . '/assets/css/themes/blue.css')
        ->prependStylesheet($this->basePath() . '/css/style.css')
        ->prependStylesheet($this->basePath() . '/assets/css/style-metronic.css')
        ->prependStylesheet($this->basePath() . '/assets/plugins/select2/select2.css')
        ->prependStylesheet($this->basePath() . '/assets/plugins/fancybox/source/jquery.fancybox.css')
        ->prependStylesheet($this->basePath() . '/assets/plugins/bootstrap/css/bootstrap.min.css')
        ->prependStylesheet($this->basePath() . '/assets/plugins/font-awesome/css/font-awesome.min.css')
    ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath() . '/js/bootstrap.min.js')
        ->prependFile($this->basePath() . '/js/jquery-2.0.3.min.js')
        ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',)); ?>

</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?php echo $this->url('home') ?>">
                <img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('Skeleton Application') ?>
            </a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a>
                </li>
            </ul>
        </div>
        <!--/.nav-collapse -->
    </div>
</nav>

<div class="page-container">
    <?php echo $this->content; ?>
</div>

<?php
$iniScript = <<<JS
var _BASEPATH = '{$this->basePath()}';
jQuery(document).ready(function () {
    App.init();
});
JS;

echo $this->inlineScript()
    ->prependScript($iniScript, 'text/javascript')
    ->prependFile($this->basePath() . '/assets/scripts/app.js', 'text/javascript')
    ->prependFile($this->basePath() . '/assets/plugins/select2/select2.js', 'text/javascript')
    ->prependFile($this->basePath() . '/assets/plugins/fancybox/source/jquery.fancybox.pack.js', 'text/javascript')
    ->prependFile($this->basePath() . '/assets/plugins/back-to-top.js', 'text/javascript')
    ->prependFile($this->basePath() . '/assets/plugins/hover-dropdown.js', 'text/javascript')
    ->prependFile($this->basePath() . '/assets/plugins/bootstrap/js/bootstrap.min.js', 'text/javascript')
    ->prependFile($this->basePath() . '/assets/plugins/jquery-migrate-1.2.1.min.js', 'text/javascript')
    ->prependFile($this->basePath() . '/assets/plugins/jquery-1.10.2.min.js', 'text/javascript')
    ->prependFile($this->basePath() . '/assets/plugins/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9'))

?>
</body>
</html>
