<?php $user = $this->identity(); ?>

    <div class="container min-hight">
        <div class="panel panel-info">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo sprintf($this->translate("%s Pages"), $user->getName()); ?></h3>
            </div>
            <div class="panel-body">

                <div class="col-md-3">
                    <?php echo $this->gravatar($user->getEmail(), array('img_size' => '180'), array('class' => 'img-responsive')); ?>
                </div>
                <div class="col-md-9">
                    <form role="form" id="contentForm" action="<?php echo $this->url('application/default', array('action' => 'getcontent', 'controller' => 'content')); ?>">
                        <div class="form-body">
                            <div class="input-group input-lg">
                                <input type="text" id="contentInput" class="form-control" placeholder="今なにをしていますか？">
                                <span class="input-group-btn"><button class="btn blue" type="button">Go!</button></span>
                            </div>
                        </div>
                    </form>

                    <div class="row margin-bottom-30" id="responseDiv" style="display: none;">
                        <div class="col-md-7 space-mobile">
                            <h2 id="titleInput"></h2>

                            <form role="form">
                                <div class="form-body">
                                    <div class="form-group">
                                        <label>Dropdown</label>
                                        <select class="form-control select2">
                                            <option>Option 1</option>
                                            <option>Option 2</option>
                                            <option>Option 3</option>
                                            <option>Option 4</option>
                                            <option>Option 5</option>
                                        </select>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label>Tag</label>
                                    <input type="text" id="tagInput" class="form-control">
                                </div>

                                <div class="form-group">
                                    <label>Comment</label>
                                    <textarea class="form-control" rows="3"></textarea>
                                </div>


                            </form>

                            <div class="row front-lists-v1">
                                <!--                                <div class="col-md-6">-->
                                <!--                                    <ul class="list-unstyled margin-bottom-20">-->
                                <!--                                        <li>-->
                                <!--                                            <i class="icon-ok"></i>-->
                                <!--                                            Officia deserunt molliti-->
                                <!--                                        </li>-->
                                <!--                                        <li>-->
                                <!--                                            <i class="icon-ok"></i>-->
                                <!--                                            Consectetur adipiscing-->
                                <!--                                        </li>-->
                                <!--                                        <li>-->
                                <!--                                            <i class="icon-ok"></i>-->
                                <!--                                            Deserunt fpicia-->
                                <!--                                        </li>-->
                                <!--                                    </ul>-->
                                <!--                                </div>-->
                                <!--                                <div class="col-md-6">-->
                                <!--                                    <ul class="list-unstyled">-->
                                <!--                                        <li>-->
                                <!--                                            <i class="icon-ok"></i>-->
                                <!--                                            Officia deserunt molliti-->
                                <!--                                        </li>-->
                                <!--                                        <li>-->
                                <!--                                            <i class="icon-ok"></i>-->
                                <!--                                            Consectetur adipiscing-->
                                <!--                                        </li>-->
                                <!--                                        <li>-->
                                <!--                                            <i class="icon-ok"></i>-->
                                <!--                                            Deserunt fpicia-->
                                <!--                                        </li>-->
                                <!--                                    </ul>-->
                                <!--                                </div>-->
                            </div>
                        </div>

                        <div class="col-md-5 front-carousel">
                            <div id="myCarousel" class="carousel slide">
                                <div class="carousel-inner" id="images">

                                </div>
                                <a class="carousel-control left" href="#myCarousel" data-slide="prev">
                                    <i class="icon-angle-left"></i>
                                </a>
                                <a class="carousel-control right" href="#myCarousel" data-slide="next">
                                    <i class="icon-angle-right"></i>
                                </a>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>

        <div class="btn-group btn-group-justified">
            <?php foreach ($categories as $category): ?>
                <a href="#" class="btn btn-default"><?php echo $category->getCategoryName(); ?></a>
            <?php endforeach; ?>
        </div>

    </div>
<?php /*
    <div class="row">
        <div class="col-md-3">
            <?php echo $this->gravatar($user->getEmail(), array('img_size' => '180'), array('class' => 'img-circle')); ?>
        </div>
        <div class="col-md-9">
            <form id="contentForm" action="<?php echo $this->url('application/default', array('action' => 'getcontent', 'controller' => 'content')); ?>">
                <div class="input-group" style="margin-top: 9%;">
                    <input type="text" class="form-control" id="contentInput"/>
                    <span class="input-group-btn"><button class="btn btn-default" type="submit">Go!</button></span>
                </div>
            </form>


            <div id="responseDiv" class="form-group" style="display: none;">
                <label for="exampleInputEmail1">Email address</label>
                <input type="text" class="form-control" id="titleInput"/>
                <ul id="images">
                </ul>
            </div>
        </div>
    </div>

    <div class="">
        <span class="testimonials-slide">Denim you probably haven't heard of. Lorem ipsum dolor met consectetur adipisicing sit amet, consectetur adipisicing elit, of them jean shorts sed magna aliqua. Lorem ipsum dolor met consectetur adipisicing sit amet do eiusmod dolore.</span>
        <div class="carousel-info">
            <img class="pull-left" src="assets/img/people/img3-small.jpg" alt=""/>

            <div class="pull-left">
                <span class="testimonials-name">Lina Doe</span>
                <span class="testimonials-post">Commercial Director</span>
            </div>
        </div>
    </div>

    <nav class="navbar navbar2 navbar-default navbar-default2" role="navigation">
        <div class="container">
            <div class="navbar-header navbar-header2">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.html">Business Casual</a>
            </div>

            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav nav2 navbar-nav navbar-nav2">
                    <li>
                        <a href="#"><?php echo $this->translate('All'); ?></a>
                    </li>
                    <?php
                    foreach ($categories as $category): ?>
                        <li>
                            <a href="#"><?php echo $category->getCategoryName(); ?></a>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
    </nav>
*/
?>
<?php
$iniScript
    = <<<JS
jQuery(document).ready(function () {
    UserIndex.init();
});
JS;

$this->inlineScript()
    ->appendFile($this->basePath() . '/js/user/index.js', 'text/javascript')
    ->appendScript($iniScript, 'text/javascript');
